version: 2.0

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk11:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk15:
    docker:
      - image: circleci/openjdk:15-buster
    steps:
      - checkout
      - run: mvn verify -V

  coverage:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V -P !build-extras -Dtest="*,!RunnerStandardIOTest,!RunnerWebSocketTest"

workflows:
  version: 2

  build-then-test:
    jobs:
      - jdk8
      - jdk11
      - jdk15
      - coverage:
          requires:
            - jdk8
            - jdk11
            - jdk15
