version: 2.1

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk11:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk15:
    docker:
      - image: circleci/openjdk:15-buster
    steps:
      - checkout
      - run: mvn verify -V

  sonar:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V -P !build-extras -Dtest="*,!RunnerStandardIOTest,!RunnerWebSocketTest" sonar:sonar -Dsonar.login=${SONAR_TOKEN}

  deploy:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: ./cd/before-deploy.sh
      - run: ./cd/deploy.sh

workflows:
  version: 2

  build-then-test:
    jobs:
      - jdk8
      - jdk11
      - jdk15
      - sonar:
          requires:
            - jdk8
            - jdk11
            - jdk15
          filters:
            branches:
              only:
                circleci-project-setup
            tags:
              only: /.*/
          context: sonarcloud
      - deploy:
          requires:
             - sonar
          filters:
            branches:
              only: circleci-project-setup
            tags:
              only: /.*/
