version: 2.1

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk11:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - checkout
      - run: mvn verify -V

  jdk15:
    docker:
      - image: circleci/openjdk:15-buster
    steps:
      - checkout
      - run: mvn verify -V

  sonar:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run: mvn verify -V -P !build-extras -Dtest="*,!RunnerStandardIOTest,!RunnerWebSocketTest"
      - sonarcloud/scan

workflows:
  version: 2

  build-then-test:
    jobs:
      - jdk8:
          filters:
            branches:
              ignore: /^dependabot.*$/
      - jdk11:
          filters:
            branches:
              ignore: /^dependabot.*$/
      - jdk15:
          filters:
            branches:
              ignore: /^dependabot.*$/
      - sonar:
          requires:
            - jdk8
            - jdk11
            - jdk15
          filters:
            branches:
              only:
                circleci-project-setup
          context: sonarcloud

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
