version: 2.1

orbs:
  maven: circleci/maven@1.0.3

workflows:
  maven_test:
    jobs:
      - maven/test:
         command: 'verify -V'
         matrix:
           parameters:
             executor: ["11.0", "15.0"]
